# Generated by Django 4.2.7 on 2026-08-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiffrement_app', '0002_signaturelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
