# Generated by Django 4.2.7 on 2026-08-27 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chiffrement_app', '0004_userprofile_avatar_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
