# Generated by Django 4.2.7 on 2026-08-28 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chiffrement_app', '0006_passkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigningKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key_pem', models.TextField()),
                ('algorithm', models.CharField(default='RSA-2048', max_length=50)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signing_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clé de signature',
                'verbose_name_plural': 'Clés de signature',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SigningChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.BinaryField()),
                ('document_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signing_challenges', to='chiffrement_app.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signing_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Défi de signature',
                'verbose_name_plural': 'Défis de signature',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_hash', models.CharField(max_length=64)),
                ('signature_value', models.TextField(help_text='Signature RSA encodée en base64')),
                ('algorithm', models.CharField(default='RSASSA-PKCS1-v1_5-SHA256', max_length=50)),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='chiffrement_app.signingchallenge')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='chiffrement_app.document')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL)),
                ('signing_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='chiffrement_app.signingkey')),
            ],
            options={
                'verbose_name': 'Signature',
                'verbose_name_plural': 'Signatures',
                'ordering': ['-signed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='signature',
            constraint=models.UniqueConstraint(fields=('document', 'signer'), name='unique_signature_per_signer_and_document'),
        ),
    ]
