# Generated by Django 4.2.7 on 2026-08-28 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def move_files_into_versions(apps, schema_editor):
    """Give every existing document a version 1 holding its current file.

    Runs before the columns are dropped, so nothing is lost. Existing
    signatures are pointed at that version: they were made against these
    bytes, which is exactly what version 1 records.
    """
    Document = apps.get_model('chiffrement_app', 'Document')
    DocumentVersion = apps.get_model('chiffrement_app', 'DocumentVersion')
    Signature = apps.get_model('chiffrement_app', 'Signature')

    for document in Document.objects.all():
        if not document.file:
            continue

        version = DocumentVersion.objects.create(
            document=document,
            version_number=1,
            file=document.file,
            sha256=document.file_hash or '',
            file_size=document.file_size,
            mime_type=document.mime_type or '',
            created_by=document.owner,
        )

        Signature.objects.filter(document=document).update(document_version=version)


def unmove_files(apps, schema_editor):
    """Put version 1 back on the document, for a clean reverse."""
    Document = apps.get_model('chiffrement_app', 'Document')

    for document in Document.objects.all():
        version = document.versions.order_by('version_number').first()

        if version is None:
            continue

        document.file = version.file
        document.file_hash = version.sha256
        document.file_size = version.file_size
        document.mime_type = version.mime_type
        document.save(update_fields=['file', 'file_hash', 'file_size', 'mime_type'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chiffrement_app', '0007_signingkey_signingchallenge_signature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('sha256', models.CharField(max_length=64)),
                ('file_size', models.BigIntegerField(null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Version de document',
                'verbose_name_plural': 'Versions de document',
                'ordering': ['-version_number'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='signature',
            name='unique_signature_per_signer_and_document',
        ),
        migrations.AddField(
            model_name='documentversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='chiffrement_app.document'),
        ),
        migrations.AddField(
            model_name='signature',
            name='document_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='chiffrement_app.documentversion'),
        ),
        migrations.AddField(
            model_name='signingchallenge',
            name='document_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signing_challenges', to='chiffrement_app.documentversion'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='unique_version_number_per_document'),
        ),
        migrations.RunPython(move_files_into_versions, unmove_files),
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_hash',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='document',
            name='mime_type',
        ),
        migrations.AddConstraint(
            model_name='signature',
            constraint=models.UniqueConstraint(fields=('document_version', 'signer'), name='unique_signature_per_signer_and_version'),
        ),
    ]
