# Generated by Django 4.2.7 on 2026-08-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiffrement_app', '0008_document_versions'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='documentsigner',
            constraint=models.UniqueConstraint(fields=('document', 'user'), name='unique_signer_per_document'),
        ),
    ]
