# Generated by Django 4.2.7 on 2026-08-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiffrement_app', '0009_unique_signer_per_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaturelog',
            name='action',
            field=models.CharField(choices=[('created', 'Document créé'), ('viewed', 'Document consulté'), ('assigned', 'Signataire affecté'), ('unassigned', 'Signataire retiré'), ('version_added', 'Nouvelle version déposée'), ('accepted', 'Accepté'), ('signed', 'Document signé'), ('rejected', 'Rejeté'), ('archived', 'Document archivé')], max_length=20),
        ),
    ]
