# Generated by Django 4.2.7 on 2026-08-28 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chiffrement_app', '0010_audit_log_actions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='signature_image',
        ),
    ]
